services:
  db:
    image: mysql:latest
    container_name: alx_backend_python
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: ALX_prodev
      MYSQL_USER: alx_user
      MYSQL_PASSWORD: alx_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: